export const COIN_TYPES = [
  'Oběžná mince',
  'Pamětní mince',
  'Investiční mince',
  'Historická mince',
  'Antická mince',
  'Středověká mince',
  'Moderní mince',
  'Zlatá mince',
  'Stříbrná mince',
  'Měděná mince',
] as const;

export const MATERIALS = [
  'Zlato',
  'Stříbro',
  'Měď',
  'Bronz',
  'Nikl',
  'Zinek',
  'Hliník',
  'Bimetalická',
  'Platina',
  'Palladium',
  'Mosaz',
  'Nerezová ocel',
] as const;

export const CURRENCIES = [
  'CZK',
  'EUR',
  'USD',
  'GBP',
  'CHF',
  'PLN',
  'HUF',
  'SEK',
  'NOK',
  'DKK',
  'CAD',
  'AUD',
  'JPY',
  'CNY',
] as const;

export const COUNTRIES = [
  'Česká republika',
  'Slovensko',
  'Německo',
  'Rakousko',
  'Francie',
  'Itálie',
  'Španělsko',
  'Portugalsko',
  'Nizozemsko',
  'Belgie',
  'Lucembursko',
  'Švýcarsko',
  'Polsko',
  'Maďarsko',
  'Slovinsko',
  'Chorvatsko',
  'Řecko',
  'Kypr',
  'Malta',
  'Finsko',
  'Estonsko',
  'Lotyšsko',
  'Litva',
  'Irsko',
  'Velká Británie',
  'Dánsko',
  'Švédsko',
  'Norsko',
  'Island',
  'USA',
  'Kanada',
  'Austrálie',
  'Nový Zéland',
  'Japonsko',
  'Čína',
  'Jižní Afrika',
  'Mexiko',
  'Brazílie',
  'Argentina',
  'Rusko',
  'Turecko',
  'Indie',
  'Singapur',
  'Hongkong',
  'Jižní Korea',
  'Thajsko',
  'Malajsie',
  'Indonésie',
  'Filipíny',
  'Vietnam',
  'Egypt',
  'Maroko',
  'Tunisko',
  'Alžírsko',
  'Libye',
  'Etiopie',
  'Keňa',
  'Tanzanie',
  'Uganda',
  'Ghana',
  'Nigérie',
  'Senegal',
  'Pobřeží slonoviny',
  'Kamerun',
  'Demokratická republika Kongo',
  'Angola',
  'Zambie',
  'Zimbabwe',
  'Botswana',
  'Namibie',
  'Lesotho',
  'Svazijsko',
  'Madagaskar',
  'Mauricius',
  'Seychely',
  'Komory',
  'Mayotte',
  'Réunion',
  'Svatá Helena',
  'Ascension',
  'Tristan da Cunha',
  'Falklandské ostrovy',
  'Jižní Georgie a Jižní Sandwichovy ostrovy',
  'Britské antarktické území',
  'Britské území v Indickém oceánu',
  'Pitcairnovy ostrovy',
  'Svatý Bartoloměj',
  'Svatý Martin',
  'Svatý Pierre a Miquelon',
  'Wallis a Futuna',
  'Francouzská Polynésie',
  'Nová Kaledonie',
  'Vanuatu',
  'Fidži',
  'Tonga',
  'Samoa',
  'Tuvalu',
  'Kiribati',
  'Nauru',
  'Palau',
  'Mikronésie',
  'Marshallovy ostrovy',
  'Severní Mariany',
  'Guam',
  'Americká Samoa',
  'Cookovy ostrovy',
  'Niue',
  'Tokelau',
  'Norfolkův ostrov',
  'Vánoční ostrov',
  'Kokosové ostrovy',
  'Heard a McDonaldovy ostrovy',
  'Antarktida',
] as const;

export const CONDITION_GRADES = [
  { value: 'P-1', label: 'Poor (P-1) - Silně opotřebovaná' },
  { value: 'FR-2', label: 'Fair (FR-2) - Opotřebovaná' },
  { value: 'AG-3', label: 'About Good (AG-3) - Téměř dobrá' },
  { value: 'G-4', label: 'Good (G-4) - Dobrá' },
  { value: 'G-6', label: 'Good (G-6) - Dobrá+' },
  { value: 'VG-8', label: 'Very Good (VG-8) - Velmi dobrá' },
  { value: 'VG-10', label: 'Very Good (VG-10) - Velmi dobrá+' },
  { value: 'F-12', label: 'Fine (F-12) - Pěkná' },
  { value: 'F-15', label: 'Fine (F-15) - Pěkná+' },
  { value: 'VF-20', label: 'Very Fine (VF-20) - Velmi pěkná' },
  { value: 'VF-25', label: 'Very Fine (VF-25) - Velmi pěkná+' },
  { value: 'VF-30', label: 'Very Fine (VF-30) - Velmi pěkná++' },
  { value: 'VF-35', label: 'Very Fine (VF-35) - Velmi pěkná+++' },
  { value: 'EF-40', label: 'Extremely Fine (EF-40) - Mimořádně pěkná' },
  { value: 'EF-45', label: 'Extremely Fine (EF-45) - Mimořádně pěkná+' },
  { value: 'AU-50', label: 'About Uncirculated (AU-50) - Téměř nepoužitá' },
  { value: 'AU-53', label: 'About Uncirculated (AU-53) - Téměř nepoužitá+' },
  { value: 'AU-55', label: 'About Uncirculated (AU-55) - Téměř nepoužitá++' },
  { value: 'AU-58', label: 'About Uncirculated (AU-58) - Téměř nepoužitá+++' },
  { value: 'MS-60', label: 'Mint State (MS-60) - Nepoužitá' },
  { value: 'MS-61', label: 'Mint State (MS-61) - Nepoužitá+' },
  { value: 'MS-62', label: 'Mint State (MS-62) - Nepoužitá++' },
  { value: 'MS-63', label: 'Mint State (MS-63) - Nepoužitá+++' },
  { value: 'MS-64', label: 'Mint State (MS-64) - Nepoužitá++++' },
  { value: 'MS-65', label: 'Mint State (MS-65) - Nepoužitá+++++' },
  { value: 'MS-66', label: 'Mint State (MS-66) - Gem' },
  { value: 'MS-67', label: 'Mint State (MS-67) - Superb Gem' },
  { value: 'MS-68', label: 'Mint State (MS-68) - Superb Gem+' },
  { value: 'MS-69', label: 'Mint State (MS-69) - Near Perfect' },
  { value: 'MS-70', label: 'Mint State (MS-70) - Perfect' },
  { value: 'PF-60', label: 'Proof (PF-60) - Proof' },
  { value: 'PF-61', label: 'Proof (PF-61) - Proof+' },
  { value: 'PF-62', label: 'Proof (PF-62) - Proof++' },
  { value: 'PF-63', label: 'Proof (PF-63) - Proof+++' },
  { value: 'PF-64', label: 'Proof (PF-64) - Proof++++' },
  { value: 'PF-65', label: 'Proof (PF-65) - Proof+++++' },
  { value: 'PF-66', label: 'Proof (PF-66) - Proof Gem' },
  { value: 'PF-67', label: 'Proof (PF-67) - Proof Superb Gem' },
  { value: 'PF-68', label: 'Proof (PF-68) - Proof Superb Gem+' },
  { value: 'PF-69', label: 'Proof (PF-69) - Proof Near Perfect' },
  { value: 'PF-70', label: 'Proof (PF-70) - Proof Perfect' },
] as const;

export const IMAGE_TYPES = [
  'obverse', // líc
  'reverse', // rub
  'edge', // hrana
  'detail', // detail
  'packaging', // balení
  'certificate', // certifikát
  'other', // ostatní
] as const;

export const IMAGE_TYPE_LABELS = {
  obverse: 'Líc',
  reverse: 'Rub',
  edge: 'Hrana',
  detail: 'Detail',
  packaging: 'Balení',
  certificate: 'Certifikát',
  other: 'Ostatní',
} as const;

export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB
export const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];

export const SEARCH_DEBOUNCE_MS = 300;
export const PAGINATION_SIZES = [12, 24, 48, 96] as const;
export const DEFAULT_PAGE_SIZE = 24;

export const TOAST_DURATION = 4000;

export const API_ENDPOINTS = {
  COINS: '/api/coins',
  IMAGES: '/api/images',
  COLLECTIONS: '/api/collections',
  STATS: '/api/stats',
  SEARCH: '/api/search',
  EXPORT: '/api/export',
} as const;

export const ROUTES = {
  HOME: '/',
  COINS: '/coins',
  COIN_DETAIL: '/coins/:id',
  ADD_COIN: '/coins/add',
  EDIT_COIN: '/coins/:id/edit',
  COLLECTIONS: '/collections',
  COLLECTION_DETAIL: '/collections/:id',
  STATS: '/stats',
  SETTINGS: '/settings',
} as const;

export const BREAKPOINTS = {
  xs: 0,
  sm: 600,
  md: 900,
  lg: 1200,
  xl: 1536,
} as const;

export const GRID_SPACING = {
  xs: 1,
  sm: 2,
  md: 3,
  lg: 4,
} as const;